import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./homepage/Navbar";
import Footer from "./homepage/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/*************  ✨ Codeium Command ⭐  *************/
/**
 * The root layout of the application.
 *
 * This component renders the main `<html>` and `<body>` elements, along with the
 * `<Navbar>` and `<Footer>` components. It also applies the Geist Sans and Geist
 * Mono fonts to the entire application.
 *
 * @param {{ children: ReactNode }} props The component props, including the
 * children to be rendered inside the layout.
/******  331a68e7-88b4-414d-b38d-ae69d18a105b  *******/
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Navbar />
          {children}
        <Footer />
      </body>
    </html>
  );
}
